apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polaris.fullname" . }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
    {{- if .Values.configMapLabels }}
    {{- tpl (toYaml .Values.configMapLabels) . | nindent 4 }}
    {{- end }}
data:
  polaris-server.yml: |-
{{ toYaml .Values.polarisServerConfig | indent 4 }}