apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "polaris.fullname" . }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
    {{- if .Values.podLabels }}
    {{- tpl (toYaml .Values.podLabels) . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "polaris.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
          {{- tpl (toYaml .Values.podAnnotations) . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "polaris.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- tpl (toYaml .Values.podLabels) . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.persistenceConfigSecret }}
      initContainers:
        - name: init-config
          image: registry.access.redhat.com/ubi9/openjdk-21:1.20-2.1721752936
          command: ['sh', '-c', 'cd /secret && jar -cf /tmp/conf.jar persistence.xml']
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: secret-volume
              mountPath: /secret
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .Values.imagePullSecrets) . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "polaris.serviceAccountName" . }}
      securityContext:
        {{- tpl (toYaml .Values.podSecurityContext) . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- tpl (toYaml .Values.securityContext) . | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ tpl .Values.image.tag . | default .Chart.Version }}"
          imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
          command: ["java"]
          args: ["-jar", "/app/polaris-service-1.0.0-all.jar", "server", "{{ trimSuffix "/" .Values.image.configDir }}/polaris-server.yml"]
          env:
            {{- if .Values.extraEnv }}
            {{- tpl (toYaml .Values.extraEnv) . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ trimSuffix "/" .Values.image.configDir }}/polaris-server.yml
              subPath: polaris-server.yml
            {{- if .Values.persistenceConfigSecret }}
            - name: tmp-volume
              mountPath: /tmp
            {{- end }}
          ports:
            {{- range $portName, $portNumber := .Values.service.ports }}
            - name: {{ $portName }}
              containerPort: {{ $portNumber }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: "polaris-metrics"
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            terminationGracePeriodSeconds: {{ .Values.livenessProbe.terminationGracePeriodSeconds }}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: "polaris-metrics"
              scheme: HTTP
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          resources:
            {{- tpl (toYaml .Values.resources) . | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "polaris.fullname" . }}
        {{- if .Values.persistenceConfigSecret }}
        - name: tmp-volume
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: {{ .Values.persistenceConfigSecret }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .Values.nodeSelector) . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- tpl (toYaml .Values.affinity) . | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- tpl (toYaml .Values.tolerations) . | nindent 8 }}
      {{- end }}
