{{- if eq .Values.polarisServerConfig.metaStoreManager.type "eclipse-link" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "polaris.fullname" . }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
    {{- if .Values.podLabels }}
    {{- tpl (toYaml .Values.podLabels) . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
          {{- tpl (toYaml .Values.podAnnotations) . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "polaris.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- tpl (toYaml .Values.podLabels) . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.persistenceConfigSecret }}
      initContainers:
        - name: init-config
          image: "{{ tpl .Values.initImage.repository . }}:{{ tpl .Values.initImage.tag . }}"
          imagePullPolicy: {{ tpl .Values.initImage.pullPolicy . }}
          command: ['sh', '-c', 'cd /secret && jar -cf /tmp/conf.jar persistence.xml']
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: secret-volume
              mountPath: /secret
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .Values.imagePullSecrets) . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "polaris.serviceAccountName" . }}
      securityContext:
        {{- tpl (toYaml .Values.podSecurityContext) . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- tpl (toYaml .Values.securityContext) . | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ tpl .Values.image.tag . | default .Chart.Version }}"
          imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
          command: ["java"]
          args: ["-jar", "/app/polaris-service-1.0.0-all.jar", "bootstrap", "{{ trimSuffix "/" .Values.image.configDir }}/polaris-server.yml"]
          volumeMounts:
            - name: config-volume
              mountPath: {{ trimSuffix "/" .Values.image.configDir }}/polaris-server.yml
              subPath: polaris-server.yml
            {{- if .Values.persistenceConfigSecret }}
            - name: tmp-volume
              mountPath: /tmp
            {{- end }}
          resources:
            {{- tpl (toYaml .Values.resources) . | nindent 12 }}
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "polaris.fullname" . }}
        {{- if .Values.persistenceConfigSecret }}
        - name: tmp-volume
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: {{ .Values.persistenceConfigSecret }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .Values.nodeSelector) . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- tpl (toYaml .Values.affinity) . | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- tpl (toYaml .Values.tolerations) . | nindent 8 }}
      {{- end }}
{{- end }}