{{- if eq .Values.polarisServerConfig.metaStoreManager.type "eclipse-link" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "polaris.fullname" . }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
    {{- if .Values.podLabels }}
    {{- tpl (toYaml .Values.podLabels) . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
          {{- tpl (toYaml .Values.podAnnotations) . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "polaris.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- tpl (toYaml .Values.podLabels) . | nindent 8 }}
        {{- end }}
    spec:
      {{- if and .Values.persistenceConfigSecret (index .Values.polarisServerConfig.metaStoreManager "conf-file") }}
      initContainers:
        - name: init-config
          image: "{{ tpl .Values.toolsImage.repository . }}:{{ tpl .Values.toolsImage.tag . }}"
          imagePullPolicy: {{ tpl .Values.toolsImage.pullPolicy . }}
          command: ["jar"]
          args: ["-cf", "/eclipselink-config/conf.jar", "-C", "/secret", "persistence.xml"]
          volumeMounts:
            - name: eclipselink-config-volume
              mountPath: /eclipselink-config
            - name: secret-volume
              mountPath: /secret
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .Values.imagePullSecrets) . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "polaris.serviceAccountName" . }}
      securityContext:
        {{- tpl (toYaml .Values.podSecurityContext) . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- tpl (toYaml .Values.securityContext) . | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ tpl .Values.image.tag . | default .Chart.Version }}"
          imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
          command: ["java"]
          args: ["-jar", "/app/polaris-service-1.0.0-all.jar", "bootstrap", "/app/config/polaris-server.yml"]
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/polaris-server.yml
              subPath: polaris-server.yml
            {{- if .Values.persistenceConfigSecret }}
            - name: eclipselink-config-volume
              mountPath: /eclipselink-config
            {{- end }}
          resources:
            {{- tpl (toYaml .Values.resources) . | nindent 12 }}
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "polaris.fullname" . }}
        {{- if and .Values.persistenceConfigSecret (index .Values.polarisServerConfig.metaStoreManager "conf-file") }}
        - name: eclipselink-config-volume
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: {{ .Values.persistenceConfigSecret }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .Values.nodeSelector) . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- tpl (toYaml .Values.affinity) . | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- tpl (toYaml .Values.tolerations) . | nindent 8 }}
      {{- end }}
{{- end }}