{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "polaris.serviceAccountName" . }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
      {{- tpl (toYaml .Values.serviceAccount.annotations) . | nindent 4 }}
    {{- end }}
{{- end }}
