name: Feature request
description: Suggest an idea for this project
title: "[FEATURE REQUEST]"
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Verify that the feature request is not already reported, looking at the [currently open issues](https://github.com/polaris-catalog/polaris/issues), use the `Filter` field to narrow down your search.

        Please provide a title above with a short, concise summary - don't leave it "empty".

        Do **NOT** share any sensitive information like password, security tokens, private URLs etc.

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    attributes:
      label: Additional context
      placeholder: |
        Add any other context or screenshots about the feature request here.
