openapi: 3.0.0

info:
  title: Apache Polaris Documentation
  x-logo:
    url: ./img/logos/polaris-catalog-stacked-logo.svg
    altText: Apache Polaris Logo
  description:
    $ref: ../docs/quickstart.md
  contact:
    email: community [at] polaris.io
    url: https://github.com/apache/polaris
  license:
    name: Apache v2.0
    url: https://github.com/apache/polaris/blob/main/LICENSE

tags:    
  - name: Overview
    description: 
      $ref: ../docs/overview.md
  - name: Polaris Entities
    description:
      $ref: ../docs/entities.md
  - name: Access Control
    description:
      $ref: ../docs/access-control.md
  - name: Configuring Polaris for Production
    description:
      $ref: ../docs/configuring-polaris-for-production.md
        